# Generated by Django 3.1.7 on 2021-03-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(choices=[('Prompt', 'Prompt'), ('Quote', 'Quote')])),
                ('content', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=250)),
                ('date_time', models.DateTimeField()),
                ('post_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.post')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.TextField(choices=[('Overseer', 'Overseer'), ('Student', 'Student')])),
                ('username', models.CharField(default='foo', max_length=255, unique=True)),
                ('password', models.CharField(default='foo', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('anonymous', models.BooleanField()),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.post'),
        ),
        migrations.CreateModel(
            name='Post_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.post')),
                ('tag_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.tags')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.meeting')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.user'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='discussion_board.user'),
            preserve_default=False,
        ),
    ]
