# Generated by Django 3.1.7 on 2021-03-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_board', '0002_auto_20210319_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='meetingusers',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='meetingusers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post_tags',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post_tags',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type_id',
            new_name='type',
        ),
    ]
